#!/bin/sh
### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage unicorn server
# Description:       Start, stop, restart unicorn server for a specific application.
### END INIT INFO
set -e

# Feel free to change any of the following variables for your app:
TIMEOUT=${TIMEOUT-60}
APP_ROOT=/home/deployer/sites/test_server/current
PID=$APP_ROOT/tmp/pids/unicorn.pid
CMD="cd $APP_ROOT; bundle exec unicorn -D -c $APP_ROOT/config/unicorn.rb -E production"
AS_USER=deployer
set -u

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

run () {
  if [ "$(id -un)" = "$AS_USER" ]; then
    eval $1
  else
    su -c "$1" - $AS_USER
  fi
}

case "$1" in

  start)
    echo >&2 "Starting $0: "
    sig 0 && echo >&2 "Already running" && exit 0
    run "$CMD"
    echo >&2 "[OK]"
  ;;

  stop)
    echo >&2 "Stopping $0: "
    sig QUIT && exit 0
    echo >&2 "[OK]"
  ;;

  restart)
    echo >&2 "Restarting $0: "
    sig QUIT && run "$CMD"
    echo >&2 "[OK]"
  ;;

  *)
    echo >&2 "Usage: $0 <start|stop|restart>"
    exit 1
  ;;
esac